const countries = [
    { "code": "AF", "name": "Afghanistan", "region": "asia" },
    { "code": "AX", "name": "Åland Islands", "region": "europe" },
    { "code": "AL", "name": "Albania", "region": "europe" },
    { "code": "DZ", "name": "Algeria", "region": "africa" },
    { "code": "AS", "name": "American Samoa", "region": "oceania" },
    { "code": "AD", "name": "Andorra", "region": "europe" },
    { "code": "AO", "name": "Angola", "region": "africa" },
    { "code": "AI", "name": "Anguilla", "region": "americas" },
    { "code": "AQ", "name": "Antarctica", "region": "antarctica" },
    { "code": "AG", "name": "Antigua and Barbuda", "region": "americas" },
    { "code": "AR", "name": "Argentina", "region": "americas" },
    { "code": "AM", "name": "Armenia", "region": "asia" },
    { "code": "AW", "name": "Aruba", "region": "americas" },
    { "code": "AU", "name": "Australia", "region": "oceania" },
    { "code": "AT", "name": "Austria", "region": "europe" },
    { "code": "AZ", "name": "Azerbaijan", "region": "asia" },
    { "code": "BS", "name": "Bahamas", "region": "americas" },
    { "code": "BH", "name": "Bahrain", "region": "asia" },
    { "code": "BD", "name": "Bangladesh", "region": "asia" },
    { "code": "BB", "name": "Barbados", "region": "americas" },
    { "code": "BY", "name": "Belarus", "region": "europe" },
    { "code": "BE", "name": "Belgium", "region": "europe" },
    { "code": "BZ", "name": "Belize", "region": "americas" },
    { "code": "BJ", "name": "Benin", "region": "africa" },
    { "code": "BM", "name": "Bermuda", "region": "americas" },
    { "code": "BT", "name": "Bhutan", "region": "asia" },
    { "code": "BO", "name": "Bolivia", "region": "americas" },
    { "code": "BQ", "name": "Bonaire, Sint Eustatius and Saba", "region": "americas" },
    { "code": "BA", "name": "Bosnia and Herzegovina", "region": "europe" },
    { "code": "BW", "name": "Botswana", "region": "africa" },
    { "code": "BV", "name": "Bouvet Island", "region": "antarctica" },
    { "code": "BR", "name": "Brazil", "region": "americas" },
    { "code": "IO", "name": "British Indian Ocean Territory", "region": "asia" },
    { "code": "BN", "name": "Brunei Darussalam", "region": "asia" },
    { "code": "BG", "name": "Bulgaria", "region": "europe" },
    { "code": "BF", "name": "Burkina Faso", "region": "africa" },
    { "code": "BI", "name": "Burundi", "region": "africa" },
    { "code": "KH", "name": "Cambodia", "region": "asia" },
    { "code": "CM", "name": "Cameroon", "region": "africa" },
    { "code": "CA", "name": "Canada", "region": "americas" },
    { "code": "CV", "name": "Cabo Verde", "region": "africa" },
    { "code": "KY", "name": "Cayman Islands", "region": "americas" },
    { "code": "CF", "name": "Central African Republic", "region": "africa" },
    { "code": "TD", "name": "Chad", "region": "africa" },
    { "code": "CL", "name": "Chile", "region": "americas" },
    { "code": "CN", "name": "China", "region": "asia" },
    { "code": "CX", "name": "Christmas Island", "region": "asia" },
    { "code": "CC", "name": "Cocos (Keeling) Islands", "region": "asia" },
    { "code": "CO", "name": "Colombia", "region": "americas" },
    { "code": "KM", "name": "Comoros", "region": "africa" },
    { "code": "CG", "name": "Congo", "region": "africa" },
    { "code": "CD", "name": "Congo, Democratic Republic of", "region": "africa" },
    { "code": "CK", "name": "Cook Islands", "region": "oceania" },
    { "code": "CR", "name": "Costa Rica", "region": "americas" },
    { "code": "CI", "name": "Côte d'Ivoire", "region": "africa" },
    { "code": "HR", "name": "Croatia", "region": "europe" },
    { "code": "CU", "name": "Cuba", "region": "americas" },
    { "code": "CW", "name": "Curaçao", "region": "americas" },
    { "code": "CY", "name": "Cyprus", "region": "asia" },
    { "code": "CZ", "name": "Czechia", "region": "europe" },
    { "code": "DK", "name": "Denmark", "region": "europe" },
    { "code": "DJ", "name": "Djibouti", "region": "africa" },
    { "code": "DM", "name": "Dominica", "region": "americas" },
    { "code": "DO", "name": "Dominican Republic", "region": "americas" },
    { "code": "EC", "name": "Ecuador", "region": "americas" },
    { "code": "EG", "name": "Egypt", "region": "africa" },
    { "code": "SV", "name": "El Salvador", "region": "americas" },
    { "code": "GQ", "name": "Equatorial Guinea", "region": "africa" },
    { "code": "ER", "name": "Eritrea", "region": "africa" },
    { "code": "EE", "name": "Estonia", "region": "europe" },
    { "code": "SZ", "name": "Eswatini", "region": "africa" },
    { "code": "ET", "name": "Ethiopia", "region": "africa" },
    { "code": "FK", "name": "Falkland Islands", "region": "americas" },
    { "code": "FO", "name": "Faroe Islands", "region": "europe" },
    { "code": "FJ", "name": "Fiji", "region": "oceania" },
    { "code": "FI", "name": "Finland", "region": "europe" },
    { "code": "FR", "name": "France", "region": "europe" },
    { "code": "GF", "name": "French Guiana", "region": "americas" },
    { "code": "PF", "name": "French Polynesia", "region": "oceania" },
    { "code": "TF", "name": "French Southern Territories", "region": "antarctica" },
    { "code": "GA", "name": "Gabon", "region": "africa" },
    { "code": "GM", "name": "Gambia", "region": "africa" },
    { "code": "GE", "name": "Georgia", "region": "asia" },
    { "code": "DE", "name": "Germany", "region": "europe" },
    { "code": "GH", "name": "Ghana", "region": "africa" },
    { "code": "GI", "name": "Gibraltar", "region": "europe" },
    { "code": "GR", "name": "Greece", "region": "europe" },
    { "code": "GL", "name": "Greenland", "region": "americas" },
    { "code": "GD", "name": "Grenada", "region": "americas" },
    { "code": "GP", "name": "Guadeloupe", "region": "americas" },
    { "code": "GU", "name": "Guam", "region": "oceania" },
    { "code": "GT", "name": "Guatemala", "region": "americas" },
    { "code": "GG", "name": "Guernsey", "region": "europe" },
    { "code": "GN", "name": "Guinea", "region": "africa" },
    { "code": "GW", "name": "Guinea-Bissau", "region": "africa" },
    { "code": "GY", "name": "Guyana", "region": "americas" },
    { "code": "HT", "name": "Haiti", "region": "americas" },
    { "code": "HM", "name": "Heard Island and McDonald Islands", "region": "antarctica" },
    { "code": "VA", "name": "Holy See", "region": "europe" },
    { "code": "HN", "name": "Honduras", "region": "americas" },
    { "code": "HK", "name": "Hong Kong", "region": "asia" },
    { "code": "HU", "name": "Hungary", "region": "europe" },
    { "code": "IS", "name": "Iceland", "region": "europe" },
    { "code": "IN", "name": "India", "region": "asia" },
    { "code": "ID", "name": "Indonesia", "region": "asia" },
    { "code": "IR", "name": "Iran", "region": "asia" },
    { "code": "IQ", "name": "Iraq", "region": "asia" },
    { "code": "IE", "name": "Ireland", "region": "europe" },
    { "code": "IM", "name": "Isle of Man", "region": "europe" },
    { "code": "IL", "name": "Israel", "region": "asia" },
    { "code": "IT", "name": "Italy", "region": "europe" },
    { "code": "JM", "name": "Jamaica", "region": "americas" },
    { "code": "JP", "name": "Japan", "region": "asia" },
    { "code": "JE", "name": "Jersey", "region": "europe" },
    { "code": "JO", "name": "Jordan", "region": "asia" },
    { "code": "KZ", "name": "Kazakhstan", "region": "asia" },
    { "code": "KE", "name": "Kenya", "region": "africa" },
    { "code": "KI", "name": "Kiribati", "region": "oceania" },
    { "code": "KP", "name": "Korea (North)", "region": "asia" },
    { "code": "KR", "name": "Korea (South)", "region": "asia" },
    { "code": "KW", "name": "Kuwait", "region": "asia" },
    { "code": "KG", "name": "Kyrgyzstan", "region": "asia" },
    { "code": "LA", "name": "Laos", "region": "asia" },
    { "code": "LV", "name": "Latvia", "region": "europe" },
    { "code": "LB", "name": "Lebanon", "region": "asia" },
    { "code": "LS", "name": "Lesotho", "region": "africa" },
    { "code": "LR", "name": "Liberia", "region": "africa" },
    { "code": "LY", "name": "Libya", "region": "africa" },
    { "code": "LI", "name": "Liechtenstein", "region": "europe" },
    { "code": "LT", "name": "Lithuania", "region": "europe" },
    { "code": "LU", "name": "Luxembourg", "region": "europe" },
    { "code": "MO", "name": "Macao", "region": "asia" },
    { "code": "MG", "name": "Madagascar", "region": "africa" },
    { "code": "MW", "name": "Malawi", "region": "africa" },
    { "code": "MY", "name": "Malaysia", "region": "asia" },
    { "code": "MV", "name": "Maldives", "region": "asia" },
    { "code": "ML", "name": "Mali", "region": "africa" },
    { "code": "MT", "name": "Malta", "region": "europe" },
    { "code": "MH", "name": "Marshall Islands", "region": "oceania" },
    { "code": "MQ", "name": "Martinique", "region": "americas" },
    { "code": "MR", "name": "Mauritania", "region": "africa" },
    { "code": "MU", "name": "Mauritius", "region": "africa" },
    { "code": "YT", "name": "Mayotte", "region": "africa" },
    { "code": "MX", "name": "Mexico", "region": "americas" },
    { "code": "FM", "name": "Micronesia", "region": "oceania" },
    { "code": "MD", "name": "Moldova", "region": "europe" },
    { "code": "MC", "name": "Monaco", "region": "europe" },
    { "code": "MN", "name": "Mongolia", "region": "asia" },
    { "code": "ME", "name": "Montenegro", "region": "europe" },
    { "code": "MS", "name": "Montserrat", "region": "americas" },
    { "code": "MA", "name": "Morocco", "region": "africa" },
    { "code": "MZ", "name": "Mozambique", "region": "africa" },
    { "code": "MM", "name": "Myanmar", "region": "asia" },
    { "code": "NA", "name": "Namibia", "region": "africa" },
    { "code": "NR", "name": "Nauru", "region": "oceania" },
    { "code": "NP", "name": "Nepal", "region": "asia" },
    { "code": "NL", "name": "Netherlands", "region": "europe" },
    { "code": "NC", "name": "New Caledonia", "region": "oceania" },
    { "code": "NZ", "name": "New Zealand", "region": "oceania" },
    { "code": "NI", "name": "Nicaragua", "region": "americas" },
    { "code": "NE", "name": "Niger", "region": "africa" },
    { "code": "NG", "name": "Nigeria", "region": "africa" },
    { "code": "NU", "name": "Niue", "region": "oceania" },
    { "code": "NF", "name": "Norfolk Island", "region": "oceania" },
    { "code": "MK", "name": "North Macedonia", "region": "europe" },
    { "code": "MP", "name": "Northern Mariana Islands", "region": "oceania" },
    { "code": "NO", "name": "Norway", "region": "europe" },
    { "code": "OM", "name": "Oman", "region": "asia" },
    { "code": "PK", "name": "Pakistan", "region": "asia" },
    { "code": "PW", "name": "Palau", "region": "oceania" },
    { "code": "PS", "name": "Palestine", "region": "asia" },
    { "code": "PA", "name": "Panama", "region": "americas" },
    { "code": "PG", "name": "Papua New Guinea", "region": "oceania" },
    { "code": "PY", "name": "Paraguay", "region": "americas" },
    { "code": "PE", "name": "Peru", "region": "americas" },
    { "code": "PH", "name": "Philippines", "region": "asia" },
    { "code": "PN", "name": "Pitcairn", "region": "oceania" },
    { "code": "PL", "name": "Poland", "region": "europe" },
    { "code": "PT", "name": "Portugal", "region": "europe" },
    { "code": "PR", "name": "Puerto Rico", "region": "americas" },
    { "code": "QA", "name": "Qatar", "region": "asia" },
    { "code": "RE", "name": "Réunion", "region": "africa" },
    { "code": "RO", "name": "Romania", "region": "europe" },
    { "code": "RU", "name": "Russia", "region": "europe" },
    { "code": "RW", "name": "Rwanda", "region": "africa" },
    { "code": "BL", "name": "Saint Barthélemy", "region": "americas" },
    { "code": "SH", "name": "Saint Helena", "region": "africa" },
    { "code": "KN", "name": "Saint Kitts and Nevis", "region": "americas" },
    { "code": "LC", "name": "Saint Lucia", "region": "americas" },
    { "code": "MF", "name": "Saint Martin", "region": "americas" },
    { "code": "PM", "name": "Saint Pierre and Miquelon", "region": "americas" },
    { "code": "VC", "name": "Saint Vincent and the Grenadines", "region": "americas" },
    { "code": "WS", "name": "Samoa", "region": "oceania" },
    { "code": "SM", "name": "San Marino", "region": "europe" },
    { "code": "ST", "name": "Sao Tome and Principe", "region": "africa" },
    { "code": "SA", "name": "Saudi Arabia", "region": "asia" },
    { "code": "SN", "name": "Senegal", "region": "africa" },
    { "code": "RS", "name": "Serbia", "region": "europe" },
    { "code": "SC", "name": "Seychelles", "region": "africa" },
    { "code": "SL", "name": "Sierra Leone", "region": "africa" },
    { "code": "SG", "name": "Singapore", "region": "asia" },
    { "code": "SX", "name": "Sint Maarten", "region": "americas" },
    { "code": "SK", "name": "Slovakia", "region": "europe" },
    { "code": "SI", "name": "Slovenia", "region": "europe" },
    { "code": "SB", "name": "Solomon Islands", "region": "oceania" },
    { "code": "SO", "name": "Somalia", "region": "africa" },
    { "code": "ZA", "name": "South Africa", "region": "africa" },
    { "code": "GS", "name": "South Georgia and the South Sandwich Islands", "region": "antarctica" },
    { "code": "SS", "name": "South Sudan", "region": "africa" },
    { "code": "ES", "name": "Spain", "region": "europe" },
    { "code": "LK", "name": "Sri Lanka", "region": "asia" },
    { "code": "SD", "name": "Sudan", "region": "africa" },
    { "code": "SR", "name": "Suriname", "region": "americas" },
    { "code": "SJ", "name": "Svalbard and Jan Mayen", "region": "europe" },
    { "code": "SE", "name": "Sweden", "region": "europe" },
    { "code": "CH", "name": "Switzerland", "region": "europe" },
    { "code": "SY", "name": "Syria", "region": "asia" },
    { "code": "TW", "name": "Taiwan", "region": "asia" },
    { "code": "TJ", "name": "Tajikistan", "region": "asia" },
    { "code": "TZ", "name": "Tanzania", "region": "africa" },
    { "code": "TH", "name": "Thailand", "region": "asia" },
    { "code": "TL", "name": "Timor-Leste", "region": "asia" },
    { "code": "TG", "name": "Togo", "region": "africa" },
    { "code": "TK", "name": "Tokelau", "region": "oceania" },
    { "code": "TO", "name": "Tonga", "region": "oceania" },
    { "code": "TT", "name": "Trinidad and Tobago", "region": "americas" },
    { "code": "TN", "name": "Tunisia", "region": "africa" },
    { "code": "TR", "name": "Türkiye", "region": "asia" },
    { "code": "TM", "name": "Turkmenistan", "region": "asia" },
    { "code": "TC", "name": "Turks and Caicos Islands", "region": "americas" },
    { "code": "TV", "name": "Tuvalu", "region": "oceania" },
    { "code": "UG", "name": "Uganda", "region": "africa" },
    { "code": "UA", "name": "Ukraine", "region": "europe" },
    { "code": "AE", "name": "United Arab Emirates", "region": "asia" },
    { "code": "GB", "name": "United Kingdom", "region": "europe" },
    { "code": "US", "name": "United States", "region": "americas" },
    { "code": "UM", "name": "United States Minor Outlying Islands", "region": "oceania" },
    { "code": "UY", "name": "Uruguay", "region": "americas" },
    { "code": "UZ", "name": "Uzbekistan", "region": "asia" },
    { "code": "VU", "name": "Vanuatu", "region": "oceania" },
    { "code": "VE", "name": "Venezuela", "region": "americas" },
    { "code": "VN", "name": "Vietnam", "region": "asia" },
    { "code": "VG", "name": "Virgin Islands (British)", "region": "americas" },
    { "code": "VI", "name": "Virgin Islands (U.S.)", "region": "americas" },
    { "code": "WF", "name": "Wallis and Futuna", "region": "oceania" },
    { "code": "EH", "name": "Western Sahara", "region": "africa" },
    { "code": "YE", "name": "Yemen", "region": "asia" },
    { "code": "ZM", "name": "Zambia", "region": "africa" },
    { "code": "ZW", "name": "Zimbabwe", "region": "africa" }
  ]
  

export default countries;